server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb
    username: root
    password: 123000
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.example.dao.entity
  mapper-Locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true